# Generated by Django 6.0.5 on 2026-08-13 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=core.models.make_object_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=80, unique=True)),
                ("title", models.CharField(max_length=160)),
                ("one_liner", models.CharField(max_length=300)),
                ("what_you_can_build", models.TextField(help_text="One concrete thing per line.")),
                (
                    "before_this",
                    models.TextField(help_text="How people did this before it existed."),
                ),
                (
                    "why_new",
                    models.TextField(help_text="What was impossible or impractical before."),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("build", "Build software"),
                            ("automate", "Automate work"),
                            ("agents", "Agents"),
                            ("media", "Media"),
                            ("interface", "Interfaces"),
                            ("infra", "Infrastructure"),
                        ],
                        default="build",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("resource_url", models.URLField(blank=True, default="")),
                ("source_url", models.URLField(blank=True, default="")),
                (
                    "became_usable_on",
                    models.DateField(
                        blank=True,
                        help_text="Roughly when this became practical for normal people.",
                        null=True,
                    ),
                ),
                ("published_on", models.DateTimeField(blank=True, null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-became_usable_on", "title"],
            },
        ),
        migrations.CreateModel(
            name="CrawlCandidate",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=core.models.make_object_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("hn_id", models.CharField(max_length=32, unique=True)),
                ("hn_title", models.CharField(max_length=500)),
                ("hn_url", models.URLField(blank=True, default="")),
                ("points", models.IntegerField(default=0)),
                (
                    "verdict",
                    models.CharField(
                        choices=[
                            ("skipped_heuristic", "Skipped (heuristic)"),
                            ("rejected_llm", "Rejected (model)"),
                            ("duplicate", "Duplicate"),
                            ("accepted", "Accepted"),
                        ],
                        max_length=32,
                    ),
                ),
                ("reason", models.TextField(blank=True, default="")),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="candidates",
                        to="syllabus.subject",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_on"],
            },
        ),
        migrations.AddIndex(
            model_name="subject",
            index=models.Index(fields=["status", "category"], name="syllabus_su_status_8661ad_idx"),
        ),
        migrations.AddIndex(
            model_name="crawlcandidate",
            index=models.Index(fields=["verdict"], name="syllabus_cr_verdict_45bde8_idx"),
        ),
    ]
