# Generated by Django 6.0.5 on 2026-08-14 22:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("syllabus", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="date_note",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Why this date and not another. Fill in when it is an editorial anchor.",
                max_length=300,
            ),
        ),
    ]
