# Generated by Django 5.2.14 on 2026-09-27 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.models


class Migration(migrations.Migration):
    dependencies = [
        ("syllabus", "0002_subject_date_note"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TopicResearch",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=core.models.make_object_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("topic", models.CharField(max_length=300)),
                ("url", models.URLField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Researching"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                        default="running",
                        max_length=20,
                    ),
                ),
                ("response_id", models.CharField(blank=True, default="", max_length=100)),
                (
                    "verdict",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("skipped_heuristic", "Skipped (heuristic)"),
                            ("rejected_llm", "Rejected (model)"),
                            ("duplicate", "Duplicate"),
                            ("accepted", "Accepted"),
                        ],
                        default="",
                        max_length=32,
                    ),
                ),
                ("reason", models.TextField(blank=True, default="")),
                ("result", models.JSONField(blank=True, default=dict)),
                ("error", models.TextField(blank=True, default="")),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="research",
                        to="syllabus.subject",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_on"],
                "indexes": [models.Index(fields=["status"], name="syllabus_to_status_251edd_idx")],
            },
        ),
    ]
